/**
 * @license
 * Copyright Borda All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://borda.dev/license
 */

/** 
 * @todo rename to DocumentRecord due to conflict with TS Record type
 */
export interface Record {
  /**
   * auto generated by rest
   */
  objectId: string;
  createdAt: string;
  updatedAt: string;
  /**
   * Date ISOString, optional.
   * when set it means session is deleted after this date.
   * by default Borda will set this to 1 year after createdAt.
   */
  expiresAt?: string;
}
