/**
 * @license
 * Copyright Intenseloop LTD All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://elegante.dev/license
 */
export interface Record {
  /**
   * auto generated by rest
   */
  objectId: string;
  createdAt: string;
  updatedAt: string;
  /**
   * Date ISOString, optional.
   * when set it means session is deleted after this date.
   * by default Elegante will set this to 1 year after createdAt.
   */
  expiresAt?: string;
}
